# Generated by Django 4.1.2 on 2024-05-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0003_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
