# Generated by Django 4.1.2 on 2024-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0004_alter_carritoitem_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
