# Generated by Django 4.1.2 on 2024-05-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0006_remove_carritoitem_marca_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
