# Generated by Django 4.1.2 on 2024-06-28 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0011_producto_codigo_producto_alter_producto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo',
        ),
    ]
