# Generated by Django 5.0.6 on 2024-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0012_remove_marca_codigo_remove_producto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='codigo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
