# Generated by Django 5.0.6 on 2024-07-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferreteria', '0013_marca_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'Retiro en tienda'), ('delivery', 'Despacho a domicilio')], default='pickup', max_length=20),
        ),
    ]
